######################################################################
# Automatically generated by qmake (3.0) ?? ?? 30 19:36:51 2014
######################################################################

TEMPLATE = app
TARGET = gotocell1
INCLUDEPATH += .
QT += widgets
# Input
FORMS += gotocelldialog.ui
SOURCES += main.cpp \
    gotocelldialog.cpp

HEADERS += \
    gotocelldialog.h
