######################################################################
# Automatically generated by qmake (3.0) ?? ??? 9 21:00:54 2014
######################################################################

TEMPLATE = app
TARGET = sort
INCLUDEPATH += .

QT += widgets
# Input
HEADERS += sortdialog.h
FORMS += sortdialog.ui
SOURCES += main.cpp sortdialog.cpp
